FROM directus/directus:latest

ARG PGHOST
ARG PGPORT
ARG PGDATABASE
ARG PGUSER
ARG PGPASSWORD

ENV \
    DB_CLIENT="pg" \
    DB_HOST=$PGHOST \
    DB_PORT=$PGPORT \
    DB_DATABASE=$PGDATABASE \
    DB_USER=$PGUSER \
    DB_PASSWORD=$PGPASSWORD
